[[rg_terms-and-definitions_section]]
== Terms and Definitions

For the purposes of this document, the following additional terms and definitions apply.

For GeoPose, specifically, the reader will consult the  <<vg-introduction-section, **Conceptual Overview Section**>> of this Guide.

[[d2d-data-definition]]
*2D data* +
Geometry of features is represented in a two-dimensional Euclidian space +
NOTE In other words, the geometry of 2D data is given using (X,Y) coordinates. +
{blank}[INSPIRE D2.8.III.2, definition 1]

[[d2d-geo-data-definition]]
*2D geographical data* +
Geometry of features is represented in a two-dimensional geographical  +
(i.e, ellipsoidal) space using (Longitude, Latitude) coordinates. +

[[d2-5d-data-definition]]
*2.5D data* +
Geometry of features is represented in a three-dimensional space with the constraint that, for each (X,Y) position, there is only one Z +
{blank}[INSPIRE D2.8.III.2, definition 2]

[[d3d-data-definition]]
*3D data* +
Geometry of features is represented in a three-dimensional space. +
NOTE In other words, the geometry of 2D data is given using (X,Y,Z) coordinates without any constraints. +
{blank}[INSPIRE D2.8.III.2, definition 3]

[[conceptual-model-definition]]
*conceptual model* +
Model that defines concepts of a universe of discourse +
{blank}[ISO 19101-1:2014, 4.1.5]

[[implementation-standard-definition]]
*implementation standard* +
Specified on the link:http://www.opengis.net/def/doc-type/is[OGC Document Types Register].
