== GeoPose for 3D Asset Formats

The world of 3D asset formats is a bewildering mess that has been adding new formats to the list as new modeling  and content creation applications and 3D content distribution platforms have appeared. This problem is generating a lot of wasted costs in the 3D asset pipelines as well as leaving lots of stakeholders frustrated. The need for standardization is apparent. Over time some notable initiatives and standardization efforts, such as the Khronos Group's glTF format that already has wide adoption as well as  the recent "Real-time Asset Creation Guidelines" from their 3D E-commerce Working Group. The Open Source USD format published by Pixar has also recently seen a lot of adoption by major players in the industry. In the spatial computing industry and in particular, for use-cases handling 3D assets with relation to the real world such as in real-world anchored AR, or 3d visualization, simulations or interactive representations of digital twins with known locations in the real world (from buildings to vehicles) there is to the knowledge of this working group not yet a standardized solution for encoding a real-world pose of 3D assets. In the glTF standards working group it has been proposed to create a GeoPose extension to the gltTF format using the OGC GeoPose standard that this document presents to reviewers.

In this document, we would like to point stakeholders who either work with or develop standards for 3D assets formats towards the opportunity of creating extensions to their formats that will comply with the OGC GeoPose encoding.

=== The Khronos Group's glTF format and GeoPose
The Khronos Gropu is an important standards body within the realm of computer graphics and hardware acceleration. They are perhaps most known for OpenGL and its variants for different platforms but also has a long history of defining standardized formats for exchanging different types of data such as 3d asset, textures, and even pre-trained neural net models. Recently they also succeeded in createing the OpenXR standard for the AR and VR industries.

Even more recently the *Geospatial Investigatory Subcommittee*, a part of the group working on the future developments of https://www.khronos.org/gltf/[glTF] opened an https://githubplus.com/DrX3D[issue] on "Geospatial Profile" where GeoPose was mentioned as part of new high-level capabilities to support geospatial applications through extensions. From the perspective of this standards effort, an extension to support assigning GeoPose directly to a widely used 3d asset format would be an important step in the right direction for interoperability between the 3d computer graphics, and geospatial industries, and we see how it can help enable some of the use-cases mentioned by the standards document such as those related to AR.

=== Pixar's open-source USD format and GeoPose
Most people recognize Pixar as a household name in the entertainment industry, responsible for a long list of blockbuster 3d animated movies from the 1995 "Toy Story" to the 2021 "Luca". They created the whole genre of full-length 3d graphics animation movies alongside creating an impressive number of technology breakthroughs in the fields of 3d graphics rendering and animation. A few years back Pixar did a major development project to unify and standardize they way different systems used by different people inside their organization could work on the same highly complex scene without the hassle of converting two and from different file formats and importing and exporting them between different systems. They came up with the https://graphics.pixar.com/usd/release/index.html[Universal Scene Description] format or "USD". Realizing that the solution to their internal interoperability issues would potentially solve industry wide interoperability problems of 3d graphics and animation they open-sourced their code code and documentation for the format in https://graphics.pixar.com/usd/release/press_opensource_release.html[2016].  In 2018 Apple decided to use a zip-archive version of USD for 3d assets used in AR applications running on the IOS platform. In 2019 NVIDIA announced they would standardize on USD for their Omniverse platform which in itself is being adopted for a range of industries such as autonomous vehicles, robotics, digital twins and city planning.  Over the last year (2021) support for USD export and import was added to a range of 3d authoring software such as  3DS Max, Maya  and Blender.

Although USD is not specified by a traditional standards body, it is developing into a defacto standard with wide adoption across a wide range of industries, and it is possible for the wider tech world to contribute and work with Pixar through the https://github.com/PixarAnimationStudios/USD[USD repo on GitHub].

The OGC GeoPose working group has done some initial research and been in early contact with the developers of the USD format. Just like with the glTF format USD allows for the creation of extensions. One potential avenue for our working group to explore would be propose a collaboration with NVIDIA who is already experienced with creating extensions for USD and has a lot of industry customers who work in the geospatial domain who would be likely to find such an extension useful.
