[[rg-landscape-standard-section]]
== Standards that Could Reference GeoPose in Normative Clauses

In this section of the reviewer's guide, we list the Standards Development Organizations (SDOs) and standards that specify <<refer to the GeoPose implementation targets in the draft spec>>[a GeoPose implementation target] as a data format. As a convention for the remainder of this section, we use the term "GeoPose" as a shorthand for any implementation target.

NOTE: Most of this is based on a transcript of Josh’s remarks during Aug 27 webinar. The https://youtu.be/Oo--VAB28BM[archive of that webinar is here].

The key question this section will answer is where and how GeoPose fits into the landscape of positioning standards. By examining some of the existing standards in detail, we will identify the gaps which GeoPose is designed to fill.

There are many existing and emerging standards for location and orientation information. They have emerged from requirements defined in different industries: aviation, planetary sciences, maritime, robotics, autonomous driving, satellite positioning and aerospace, to name a few. There is good practice in commercial and other domains for expressing the location and orientation of entities in all these fields. These existing standards cover different scales, for different purposes, different information environment: sometimes graphical, sometimes geospatial.

= Pipeline of interoperability needs
There are conceptual and actual data pipelines that connect the real world and the objects in it with the representations in information and graphics systems. A number of the critical standards define how those pipelines are developed and interoperate or fit together.

On the Web, information is displayed on a plane. There is a need for a standard to get the information from the Web into that display plane in a manner that is sufficiently fast to provide XR experiences. W3C WebXR focuses on this need.

In order to establish this data flow, there is a need in real graphics systems to locate those objects within a 3D local stage (or scene) so that when the user’s head or perceived objects move within that “stage”, the graphics systems can address that correctly. Khronos OpenXR focuses on that stage of the pipeline.

On the other side, the OGC has been working on how sensor systems measure these changes in location and orientation. How does a system model the sensor that’s capturing all the data about the features (e.g., objects) in its environment, including where they are and how the system represents them in a local 2D or 3D environment? OGC Sensor Web Enablement, particularly Observations & Measurements and SensorML, addresses these needs.

Each of these stages in the pipeline need to exchange data between themselves. How do you get the location and orientation of anything from anywhere to anywhere, into and out of these interactive environments? That’s where GeoPose comes in.

= GeoPose 

GeoPose provides the connection. This is important for both integration and mediation, aspects of data interoperability. Anything might be positioned where it could be of concern or of interest in this pipeline.

The primary source of inspiration for GeoPose was the NASA SPICE framework because it is able to cover any scale from interplanetary and interstellar to specific local objects. NASA designed SPICE to address significant challenges in looking at both ephemeris objects (fixed, or on predictable paths) and objects that have changeable locations and orientations such as satellites, cameras, and other sensors. Representing different frames for these objects and being able to transform between them is really useful. SPICE is a formalism that is much larger than one needs for a simple or basic implementation, but an incredibly appropriate foundation from which the SWG was inspired.

OGC Moving Features is also a very useful standard to consider and was taken into account when GeoPose was designed. Although it describes object position and orientation, Moving Features (MF) is focused on a particular set of use cases with an emphasis on sensor streams, digital exhausts, and location information (usually GPS) coming off of vehicles in a municipal environment. It tries to accomplish this in as efficient a manner as possible so that the data can be incorporated into analytical and visual applications.

There is quite a lot of compatibility between Moving Features, which is an existing and evolving standard, and GeoPose which is in its initial phase of deployment. They have distinct roles. MF focuses on a local, municipal scale, and rapid streams of measurements. Getting observations in and out of municipal management and other platforms easily and efficiently is one of the roles that GeoPose can play.

There is another OGC standard that deals with how to work with sensors and getting useful observations out of them. On the right of this figure is a schematic showing the workflows that are enabled in Observations and Measurements, in Semantic Sensor Networks, and with encodings such as SWE Common that enable transport of sensor outputs (observations). Another important part of these standards, SensorML, models the sensor process itself, from an initial environmental stimulus to how a measurement is recorded as an observation and recognized as an observed property of a real world object.

If this is a directed sensor (e.g. camera), orientation is an essential aspect of the sensor model. The result potentially includes the positions and orientations of both the sensor / platform and any observed entities in the world, although the sensor position and orientation may be secondary  to the primary objective of observing the positions and orientations of these observed entities, e.g. cars. GeoPose permits systems to get the position and orientation in and out of SWE-compliant platforms or devices without losing any resolution or introducing delays.

Turning to some of the other environments of position and orientation.


Khronos OpenXR also deals with poses, particularly within specific spaces (frames of reference). It defines a set of reference spaces: view, local and stage. OpenXR specifies the model which graphics hardware can deal with and this model is then to be implemented in those devices. Within a particular graphical system, it is effective. But bringing a pose from anything from anywhere is where GeoPose comes in

In the web and the web browser end of things, poses need to move from Web content (pages and resources) to various hardware devices that are web enabled, such as heads-up browsers. This has the problem “what is the content that is compatible with this and what information should be processed through the user’s equipment to bring anything from anywhere on the web, which represents anything from anywhere in the world, or which can be placed into the the user’s world from virtual entity definitions.

To summarize, there are a number of very useful, rigorous, well-developed standards for position and orientation. What they lack is a means for 6DOF information to flow between them in a manner that is independent of graphical system, applications scene, frame of reference, and technology. GeoPose will offer the portability (interoperability) of information across all these domains and systems.

We know that pose is essential for combining physical and digital entities in visual scenes so that they can be experienced by a service or a user, particularly if you really want to cast a wide, even global net for appropriate entities, wherever the scene and observer may happen to be located. Geocentric (earth-based) location and orientation are the basis for all these integrations.  OGC GeoPose provides that usable common ground, both the geospatial expertise that OGC has cultivated for many years and digital representation of physical space as the most common denominator among all these systems and representations.

=======
The table to be used in this section has not yet been discussed and decided upon.

Within the table, we need links to the standards themselves. The link needs to be a human readable (in another column)

1. References (definitive reference) is a citation

Also, must create a table dedicated to IEEE Standards. What are the IEEE standards?


Here are notes about two standards that have not yet been put into the table.

This URL is a convenient place to view many space data standards
URL: http://spacedatastandards.org/


From BuildingSMARTS IFC4 BIM standard there is the concept of an "IFc Site". It lets users provide the WGS84 location (lat,lng,alt) of  "the single geographic reference point for this site "
http://standards.buildingsmart.org/MVD/RELEASE/IFC4/ADD2_TC1/RV1_2/HTML/schema/ifcproductextension/lexical/ifcsite.htm
For orientation they refer to the concept of "true north": "The world coordinate system, established at the IfcProject.RepresentationContexts, may include a definition of the true north within the XY plane of the world coordinate system, if provided, it can be obtained at IfcGeometricRepresentationContext.TrueNorth."


__OGC Standards__

The OGC has a number of positioning and location standards. Some also express orientation and they do so in different scales and with different global and/or local coordinate reference systems. Some also deal with different time scales.


Some standards (such as OGC CDB) deal with fixed infrastructure, or with somewhat more specialized information, such as KML and IndoorGML. Some deal with expressing location and orientation in very dynamic and real time scales, such as Sensor Web Enablement and Moving Features.

|===
|*Standard* |*Relevant Section* |*Quote the Text*

|Moving Features
|Cell in column 2
|Cell in column 3

|Sensor Web Enablement (SWE)
|Cell in column 2
|Cell in column 3

|CityGML
|Cell in column 2
|Cell in column 3

|IndoorGML
|Cell in column 2
|Cell in column 3

|CDB (Common DataBase)
|Cell in column 2
|Cell in column 3

|KML (??)
|Cell in column 2
|Cell in column 3
|===

Other SDOs
There are other standards development organizations (SDO’s) that deal with location and orientation for graphics. Work done in the W3C defines how systems express location and orientation for browsers. The Motion Imagery Standards Board (MISB) has standards for moving cameras. ISO also has sections of its standards in SC 24, such as the X3D standards, that encode orientation and position in graphics. In the Khronos Group, there are standards such as OpenXR and glTF that specify how to form digital assets that encode position and orientation


__Khronos Group__
|===
|*Standard* |*Relevant Section* |*Quote the Text*

|glTF
|Cell in column 2
|Cell in column 3

|OpenXR
|link:https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XR_MSFT_spatial_anchor[Extension for Microsoft Spatial Anchors]
|This extension allows an application to create a spatial anchor, an arbitrary freespace point in the user’s physical environment that will then be tracked by the runtime. The runtime should then adjust the position and orientation of that anchor’s origin over time as needed, independently of all other spaces and anchors, to ensure that it maintains its original mapping to the real world.

|OpenVX
|Cell in column 2
|Cell in column 3

|OpenKCam
|Cell in column 2
|Cell in column 3
|===

__W3C__
|===
|*Standard* |*Relevant Section* |*Quote the Text*

|Geolocation API
|Cell in column 2
|Cell in column 3

|Browser Sensor Interfaces
|Cell in column 2
|Cell in column 3

|Immersive Web WebXR Device API
|link:https://immersive-web.github.io/webxr/#xrspace-interface[XRSpace] and link:https://immersive-web.github.io/webxr/#pose[XR Pose]
|An XRSpace represents a virtual coordinate system with an origin that corresponds to a physical location. Spatial data that is requested from the API or given to the API is always expressed in relation to a specific XRSpace at the time of a specific XRFrame. Numeric values such as pose positions are coordinates in that space relative to its origin. The interface is intentionally opaque.
|===

__Motion Imagery Standards Board (MISB)__
|===
|*Standard* |*Relevant Section* |*Quote the Text*

|MISB ST 0601
|Cell in column 2
|Cell in column 3

|MISB ST 0801.5
|Cell in column 2
|Cell in column 3
|===

__ASTM__
|===
|*Standard* |*Relevant Section* |*Quote the Text*

|E57
|link:http://libe57.org/features.html[defines fifteen features that cover the core capabilities of the E57 format]
|Cell in column 3

|===

There are also specifications (standards) that are developed for and used by industries/domains.

Space
The Observation Geometry System NASA uses for Space Science Missions is called SPICE.
A tutorial presentation about SPICE is available link:https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/Tutorials/pdf/individual_docs/03_spice_overview.pdf[here].

__NASA__
|===
|*Standard* |*Relevant Section* |*Quote the Text*

|SPICE
|link:https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/Tutorials/pdf/individual_docs/21_fk.pdf[Frame Kernel]
|Cell in column 3

|===
