[[ug_references_section]]
== References
The following documents contain provisions that, through reference in this text, constitute provisions of this Users Guide. For dated references, subsequent amendments to, or revisions of, any of these publications do not apply. For undated references, the latest edition of the document referred to applies.

* [[rfc2045,RFC 2045]] IETF: RFC 2045 & 2046, Multipurpose Internet Mail Extensions (MIME). (November 1996),
* [[rfc3986,RFC 3986]] IETF: RFC 3986, Uniform Resource Identifier (URI): Generic Syntax. (January 2005)
* [[inspirebu,INSPIRE: D2.8.III.2]] INSPIRE: D2.8.III.2 Data Specification on Buildings – Technical Guidelines. European Commission Joint Research Centre.
* [[iso19101,ISO 19101-1:2014]] ISO: ISO 19101-1:2014, Geographic information - Reference model - Part 1: Fundamentals

NOTE: Each reference has an anchor. That allows users to jump to this citation from any hyperlinked reference in the text. The second part of the anchor is the text that will be displayed such as <<rfc2045>>
